name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:

jobs:
  run_tests:
    name: Run tests and attempt build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
            node-version: 12
      - run: yarn install
      - run: yarn run test
      - run: yarn run build

